# Generated by Django 5.0.6 on 2024-06-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="token",
        ),
        migrations.AddField(
            model_name="customuser",
            name="middle_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
