# Generated by Django 5.0.6 on 2024-07-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_customuser_token_customuser_middle_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_changed",
            field=models.BooleanField(default=False),
        ),
    ]
