# Generated by Django 5.0.6 on 2024-07-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_password_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="level",
            field=models.CharField(default="100", max_length=5),
        ),
    ]
