# Generated by Django 5.0.6 on 2024-12-06 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="entry_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(default="000", max_length=50),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="level",
            field=models.CharField(blank=True, default="100", max_length=5),
        ),
    ]
