# Generated by Django 5.0.6 on 2024-06-26 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_remove_candidate_first_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Candidate",
            ),
        ),
        migrations.AlterField(
            model_name="election",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.UniqueConstraint(
                fields=("user", "election", "position"),
                name="unique_candidate_position",
            ),
        ),
    ]
