# Generated by Django 5.0.6 on 2024-06-26 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_candidate_user_alter_election_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="candidate",
            name="unique_candidate_position",
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.UniqueConstraint(
                fields=("user", "election"), name="unique_candidate_position"
            ),
        ),
    ]
