# Generated by Django 5.0.6 on 2024-06-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_remove_candidate_unique_candidate_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
