# Generated by Django 5.0.6 on 2024-06-28 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_election_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vote",
            name="unique_voter_position",
        ),
        migrations.AddField(
            model_name="vote",
            name="position",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="polls.position",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="polls.candidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("voter", "election", "position"), name="unique_voter_position"
            ),
        ),
    ]
