# Generated by Django 5.0.6 on 2024-07-12 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_election_results_published_alter_candidate_election_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate",
                to="polls.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="election",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="election",
                to="polls.election",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="position",
                to="polls.position",
            ),
        ),
    ]
