# Generated by Django 5.0.6 on 2024-07-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_votetoken_remove_vote_unique_voter_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
